### ISSUE TITLE
Is this different from keychain?

### ISSUE THREAD

**Issue by perpetual-hydrofoil** [mvk/sshadder#12]
i.e., I add this to my .bashrc:

[ -f $HOME/.ssh/id_ed25519_2017 ] && keychain $HOME/.ssh/id_ed25519_2017

Then whenever I start up a term, drobbins' GNU keychain checks to see if ssh-agent is running and adds my key(s) to it (using one of the ssh-askpass's to securely get the password).

I didn't quite understand the theory of operation on the pypi page. Does it prompt for another crypto key that's different from the ssh passphrase? (if so, why?)

Looks purty neat otherwise, though. I love simple, clean tools. (userify!)

**Comment by mvk** [comment]
hi, @jamiesonbecker 
Thank you for your interest.

The short answer is: **YES**

## Longer version
If I understand GNU keychain correctly, I can implement it using a "canary" file sourcing with agent env variables in and try and detect whether it points to really live ssh-agent.
This still forces me to type in all the keys' passwords each time, which is the bummer I am trying to avoid.

So the use case I want to cover is: I have to have multiple ssh keys *protected by different passwords* 4-5 or even more. So at boot up, I have to waste several minutes typing different passwords just to be able to connect to systems.
I am trying to speed up this  "post boot up" initialization based on 1 "master password".
This way in less than 1 minute I can connect.
Yet, I want to keep the keys' passwords **relatively** safe.

Can you advice me how to do it best ?

I know I am currently doing several sins in safety:
* mixing sensitive and insensitive data in my config JSON file
* keeping the keys on my hard disk, instead of removable media
* keeping the config JSON on local hard disk
* using pexpect is probably not the best practice...


For now I am content with the functionality as it is.

But I also do not mind switching language, given the abundance of libraries, this glueware should be thin and stupid, and easy to implement in any language. 
Probably using languages like Go/C/C++ would be the right call, eventually.

So the real question is - how many people are interested in this use case?


And, incidentally I am not a cryptography expert :)
If there is traction with people, I would start doing things better, of course

**Comment by mvk** [comment]
@jamiesonbecker For now I am content with the functionality as it is.

But I also do not mind switching language, given the abundance of libraries, this glueware should be thin and stupid, and easy to implement in any language. 
Probably using languages like Go/C/C++ would be the right call, eventually.

So the real question is - how many people are interested in this use case?

**Comment by perpetual-hydrofoil** [comment]
Hi Mkv,

Well, now at least I understand your quest!

I have to question why it's so challenging to type multiple passphrases. ;) (Or, why run so many keys.) But, I agree with you that this scheme is insufficiently secure and you seem pretty honest about that. (The built-in ssh key passphrase encryption model is pretty secure, especially with local disk encryption) See also: https://security.stackexchange.com/questions/18197/why-shouldnt-we-roll-our-own Switching languages won't really help you there (and would possibly hurt). But I love your passion for this stuff and that's the way to learn, so perhaps you can bring value to some existing crypto projects.

You don't gain anything by running lots of keys on the same system (unless you're rotating and keeping the old one around during the transition, but Userify can help you do that instantly instead), and it's a lot of extra complexity to manage. In other words, if someone pwns your home directory or system, they have all those keys anyway, especially with one password to rule them all. Complexity is the enemy of security, so if you can reduce the number of keys you're running it's better. (If you have multiple clients, you can give the same public key to each. You can even change the comment field for the public key for each client.)

One situation where I suggest running multiple keys is one per device. For example, it might be slightly easier to revoke a single key from your desktop when you leave your laptop in the airport or your phone is stolen (or whatever). Other than that, one key is usually enough.

Hope this helps! Keep up the passion for security and crypto.. it's a lot of fun and will pay off one day!

-Jamieson

**Comment by perpetual-hydrofoil** [comment]
Oh, one more thought... keychain actually is designed to decrypt your key and keep it in memory. If you don't have a keychain or ssh-agent set up properly, then you'd have to type in your passphrase each time, which quickly gets old :) Unfortunately, some systems don't easily call .bashrc. You really would need to make sure that you see something happening in .bashrc. Then it's just one time to unlock your key per boot. Be sure to encrypt your disk and swap, as the unencrypted key could get swapped out to disk during hibernate on your laptop.

**Comment by mvk** [comment]
@jamiesonbecker thanks for explaining.
It would make my life easier had I the option to not use multiple keys.
But this is a bit out of scope of this thread :)
I am fully aware I would love not to have to mess with all of them, and have 1 password.
We then would not have this chat :)
Let's assume for the sake of this tool's viability I do have to use multiple key pairs.
Also, LUKS is in-place.

now, action items

* you've implicitly suggested to replace pexpect with ssh-askpass mechanism. I'll do this.
* is keeping the config file partially encrypted a big no-no ?

I can try cooperating with ansible-vault programmatically to keep the whole json/yaml, and load it using python api, 

P.S.
which dc's is userify service using in the 'saas' offering?

**Comment by perpetual-hydrofoil** [comment]
Hi Mvk! Sounds good :) I actually haven't look at it in detail.. but def suggest isolating secure data from insecure data. Thanks for asking!! We just migrated from AWS to vultr to reduce bandwidth costs (static storage still S3), but we're going to be migrating over to our other partner (Google) shortly at least for core operating VM's. Vultr has a really neat BGP networking option that we haven't seen elsewhere, and Google's virtual private clouds can span continents, which is pretty cool. (I'm an AWS certified SA but I find that minor limitation a bit frustrating at times). We also run most static files from Digital Ocean (bandwidth again -- we use a metric ton of bandwidth), and CDN via CloudFront for our website etc.
